import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  OneToMany,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { Post } from '../post/post.entity';
import { FieldReport } from '../field-report/field-report.entity';
import { Cluster } from '../cluster/cluster.entity';

@Entity('pages')
export class Page {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column({ nullable: true })
  username: string;

  @Column({ nullable: true })
  platform: string; // instagram, telegram, twitter, etc.

  @Column({ nullable: true })
  category: string; // topical cluster — see TOPICAL_CLUSTERS in shared constants (technology, marketing, science, quran, eulogy, mysticism, parenting, beauty, fashion, art, music, photography, anime_games, news_politics, environment, comedy, dance, travel, history, sports, cooking, military, business_crypto, social_legal, medicine)

  @Column({ nullable: true, default: null })
  category_source: string; // 'manual' or 'ai' — tracks who set the category

  @Column({ nullable: true })
  identity_category: string; // who owns the page — see IDENTITY_CATEGORIES (journalist, lifestyle_blogger, influencer, comedian, cleric, eulogist, academic, civic_activist, artist_singer, kid_parent_blogger, hijab_blogger, expert, corporate, athlete, tourist)

  @Column({ nullable: true, default: null })
  identity_category_source: string; // 'manual' or 'ai'

  @Column({ nullable: true })
  country: string;

  @Column({ nullable: true })
  nationality: string; // ملیت — distinct from country (e.g. ایرانی، عربی، ترک)

  @Column({ nullable: true })
  language: string; // primary content language

  @Column({ nullable: true })
  content_language: string; // dominant production language ("80% of posts" rule, or "multilingual" if mixed)

  @Column({ nullable: true })
  religion: string; // دین و مذهب (e.g. شیعه، سنی، مسیحی، بی‌دین، نامشخص)

  @Column({ nullable: true })
  gender: string; // جنسیت (male, female, mixed, unknown)

  @Column({ nullable: true })
  age_range: string; // رده‌سنی (under_18, 18_25, 25_35, 35_50, over_50, unknown)

  @Column({ type: 'int', default: 0 })
  followers_count: number;

  @Column({ type: 'int', default: 0 })
  following_count: number;

  @Column({ nullable: true })
  bio: string;

  @Column({ nullable: true })
  profile_image_url: string;

  // Canonical profile URL of the source (added as nullable column in the
  // Phase 2 migration Phase2NetworksActors). Distinct from profile_image_url.
  @Column({ nullable: true })
  profile_url: string;

  // Operational network this source belongs to (added as nullable column in the
  // Phase 2 migration Phase2NetworksActors; FK → networks.id, ON DELETE SET NULL).
  @Column({ type: 'int', nullable: true })
  network_id: number | null;

  @Column({ nullable: true })
  cluster: string; // semantic cluster label (free text label from LLM)

  // Membership in a managed cluster (one-to-many).
  @Column({ type: 'int', nullable: true })
  cluster_id: number | null;

  @ManyToOne(() => Cluster, (cluster) => cluster.pages, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'cluster_id' })
  cluster_ref: Cluster | null;

  // Whether this page is treated as a representative (نماینده) of its cluster.
  // Representatives drive the "نمایندگان شبکه" scope in dashboards.
  @Column({ type: 'boolean', default: false })
  is_representative: boolean;

  @Column({ type: 'float', default: 0 })
  credibility_score: number;

  @Column({ type: 'float', default: 0 })
  influence_score: number;

  @Column({ type: 'float', default: 0 })
  consistency_rate: number; // پایداری

  @Column({ type: 'float', default: 0 })
  affinity_score: number; // همراهی / Loyalty

  @Column({ type: 'float', default: 0 })
  alignment_score: number; // همسویی — مخالفت با آمریکا/اسرائیل/امارات/عربستان و حمایت از فلسطین/لبنان/یمن/مقاومت عراق/جمهوری اسلامی

  @Column({ type: 'float', default: 0 })
  avg_likes: number; // میانگین لایک ۱۰ پست انتهایی

  @Column({ type: 'float', default: 0 })
  avg_comments: number; // میانگین کامنت ۱۰ پست انتهایی

  @Column({ type: 'float', default: 0 })
  engagement_rate: number; // ((avg_likes + avg_comments) / followers_count) × 100

  @Column({ type: 'int', default: 0 })
  posts_count: number; // تعداد کل پست‌های ثبت‌شده

  @Column({ type: 'jsonb', nullable: true })
  persona_radar: Record<string, number>; // 6-axis: aggressive/defensive, producer/resharer, visual/textual, formal/informal, local/global, interactive/one-way

  @Column({ type: 'jsonb', nullable: true })
  pain_points: string[]; // top 3 concerns

  @Column({ type: 'jsonb', nullable: true })
  keywords: string[];

  // === Narrative profile (generated by dedicated LLM call) ===

  @Column({ type: 'text', nullable: true })
  narrative_description: string | null; // 200-300 word free description: interests, key people, political/social view, narrative style

  @Column({ type: 'text', nullable: true })
  audience_description: string | null; // description of followers / audience

  @Column({ type: 'text', nullable: true })
  engagement_suggestion: string | null; // suggested interaction approach (Persian)

  @Column({ type: 'jsonb', nullable: true })
  engagement_suggestion_translations: Record<string, string> | null; // {en, ar, es, tr, ur}

  @Column({ type: 'jsonb', nullable: true })
  topic_distribution: Array<{ topic: string; min_percent: number; max_percent: number }> | null; // approximate distribution of post + story themes

  @Column({ type: 'timestamp', nullable: true })
  narrative_generated_at: Date | null;

  @Column({ default: true })
  is_active: boolean;

  @Column({ nullable: true })
  page_category: string; // official, news_agency, fan_pages, etc.

  @Column({ type: 'jsonb', nullable: true })
  client_keywords: string[]; // keywords for filtering relevant posts

  @Column({ type: 'timestamp', nullable: true })
  last_fetched_at: Date;

  @Column({ type: 'timestamp', nullable: true })
  last_processed_at: Date;

  @Column({ nullable: true })
  last_processed_timeframe: string; // e.g. '24h', '1w', '1m', 'all'

  @OneToMany(() => Post, (post) => post.page)
  posts: Post[];

  @OneToMany(() => FieldReport, (report) => report.page)
  field_reports: FieldReport[];

  @CreateDateColumn({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP(6)' })
  created_at: Date;

  @UpdateDateColumn({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP(6)', onUpdate: 'CURRENT_TIMESTAMP(6)' })
  updated_at: Date;
}
